swagger: "2.0"
info:
  title: Argent Bank Transaction API
  description: API model for user transactions
  version: 2.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/ph2
schemes:
  - http
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Transactions In The Current Month
      description: Fetching Current Month Transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User transactions returned successfully
          schema:
            $ref: "#/definitions/detailledTransactionResponse"
        "400":
          description: Invalid
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
  /user/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Transaction Add API
      description: API to add transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Neccessary data to create a new transaction
          required: true
          schema:
            $ref: "#/definitions/addTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction added successfully
          schema:
            $ref: "#/definitions/ApiTransactionResponse"
        "400":
          description: Invalid data
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /user/transaction/{idTr}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Transaction Show API
      description: Detailled transaction view API
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idTr
          description: transaction's Id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction returned successfully
          schema:
            $ref: "#/definitions/ApiTransactionResponse"
        "400":
          description: Invalid
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Transaction Edit API
      description: transaction's updt API
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idTr
          description: transaction's id that will be edited
          required: true
          type: string
        - in: body
          name: body
          description: Edit transaction
          required: true
          schema:
            $ref: "#/definitions/editTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction edited successfully
          schema:
            $ref: "#/definitions/ApiTransactionResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Transaction Delete API
      description: delete transaction API
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idTr
          description: transaction's ID that will be deleted
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction deleted successfully
        "400":
          description: Invalid
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  detailledTransactionResponse:
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          ## list of currents transactions
          transaction_1:
            type: object
            description: First transaction in the current month
            properties:
              id:
                type: string
                description: first transaction's Id
              date:
                type: string
                description: first transaction's Date
              amount:
                type: number
                description: first transaction's Amount
              description:
                type: string
                description: first transaction's Description
          transaction_2:
            type: object
            description: Second transaction in the current month
            properties:
              id:
                type: string
                description: second transaction's Id
              date:
                type: string
                description: second transaction's Date
              amount:
                type: number
                description: second transaction's Amount
              description:
                type: string
                description: second transaction's Description
            ## n transactions
  ApiTransactionResponse:
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: transaction's Id
          date:
            type: string
            description: transaction's Date
          amount:
            type: number
            description: transaction's Amount
          description:
            type: string
            description: transaction's Description
          category:
            type: string
            description: transaction's Category
          notes:
            type: string
            description: transaction's Notes
  addTransaction:
    properties:
      accountId:
        type: string
        description: new transaction's AccountId containing
      amount:
        type: number
        description: new transaction's Amount
      description:
        type: string
        description: new transaction's Description
      category:
        type: string
        description: new transaction's Category
      notes:
        type: string
        description: new transaction's Notes
  editTransaction:
    properties:
      description:
        type: string
        description: New description
      category:
        type: string
        description: New category of this transaction
      notes:
        type: string
        description: New notes of this transaction
